// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.1
// source: proto/node/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_proto_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_proto_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_node_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{2}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_node_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigResponse) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_node_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Running        bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	SingboxVersion string                 `protobuf:"bytes,2,opt,name=singbox_version,json=singboxVersion,proto3" json:"singbox_version,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Inbounds       int32                  `protobuf:"varint,4,opt,name=inbounds,proto3" json:"inbounds,omitempty"`
	Outbounds      int32                  `protobuf:"varint,5,opt,name=outbounds,proto3" json:"outbounds,omitempty"`
	LastUpdateUnix int64                  `protobuf:"varint,6,opt,name=last_update_unix,json=lastUpdateUnix,proto3" json:"last_update_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_node_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetStatusResponse) GetSingboxVersion() string {
	if x != nil {
		return x.SingboxVersion
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetInbounds() int32 {
	if x != nil {
		return x.Inbounds
	}
	return 0
}

func (x *GetStatusResponse) GetOutbounds() int32 {
	if x != nil {
		return x.Outbounds
	}
	return 0
}

func (x *GetStatusResponse) GetLastUpdateUnix() int64 {
	if x != nil {
		return x.LastUpdateUnix
	}
	return 0
}

var File_proto_node_node_proto protoreflect.FileDescriptor

const file_proto_node_node_proto_rawDesc = "" +
	"\n" +
	"\x15proto/node/node.proto\x12\x04node\"6\n" +
	"\x13UpdateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"<\n" +
	"\x14UpdateConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10GetConfigRequest\"4\n" +
	"\x11GetConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"\x12\n" +
	"\x10GetStatusRequest\"\xe1\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12'\n" +
	"\x0fsingbox_version\x18\x02 \x01(\tR\x0esingboxVersion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1a\n" +
	"\binbounds\x18\x04 \x01(\x05R\binbounds\x12\x1c\n" +
	"\toutbounds\x18\x05 \x01(\x05R\toutbounds\x12(\n" +
	"\x10last_update_unix\x18\x06 \x01(\x03R\x0elastUpdateUnix2\xd0\x01\n" +
	"\vNodeService\x12E\n" +
	"\fUpdateConfig\x12\x19.node.UpdateConfigRequest\x1a\x1a.node.UpdateConfigResponse\x12<\n" +
	"\tGetConfig\x12\x16.node.GetConfigRequest\x1a\x17.node.GetConfigResponse\x12<\n" +
	"\tGetStatus\x12\x16.node.GetStatusRequest\x1a\x17.node.GetStatusResponseB)Z'github.com/CascadiaLabs/node/proto/nodeb\x06proto3"

var (
	file_proto_node_node_proto_rawDescOnce sync.Once
	file_proto_node_node_proto_rawDescData []byte
)

func file_proto_node_node_proto_rawDescGZIP() []byte {
	file_proto_node_node_proto_rawDescOnce.Do(func() {
		file_proto_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_node_proto_rawDesc), len(file_proto_node_node_proto_rawDesc)))
	})
	return file_proto_node_node_proto_rawDescData
}

var file_proto_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_node_node_proto_goTypes = []any{
	(*UpdateConfigRequest)(nil),  // 0: node.UpdateConfigRequest
	(*UpdateConfigResponse)(nil), // 1: node.UpdateConfigResponse
	(*GetConfigRequest)(nil),     // 2: node.GetConfigRequest
	(*GetConfigResponse)(nil),    // 3: node.GetConfigResponse
	(*GetStatusRequest)(nil),     // 4: node.GetStatusRequest
	(*GetStatusResponse)(nil),    // 5: node.GetStatusResponse
}
var file_proto_node_node_proto_depIdxs = []int32{
	0, // 0: node.NodeService.UpdateConfig:input_type -> node.UpdateConfigRequest
	2, // 1: node.NodeService.GetConfig:input_type -> node.GetConfigRequest
	4, // 2: node.NodeService.GetStatus:input_type -> node.GetStatusRequest
	1, // 3: node.NodeService.UpdateConfig:output_type -> node.UpdateConfigResponse
	3, // 4: node.NodeService.GetConfig:output_type -> node.GetConfigResponse
	5, // 5: node.NodeService.GetStatus:output_type -> node.GetStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_node_node_proto_init() }
func file_proto_node_node_proto_init() {
	if File_proto_node_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_node_proto_rawDesc), len(file_proto_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_node_proto_goTypes,
		DependencyIndexes: file_proto_node_node_proto_depIdxs,
		MessageInfos:      file_proto_node_node_proto_msgTypes,
	}.Build()
	File_proto_node_node_proto = out.File
	file_proto_node_node_proto_goTypes = nil
	file_proto_node_node_proto_depIdxs = nil
}
